# Site Settings
locale: "en-US"
title: "flippermen | Ciberseguridad y Hacking Ético"
description: "Artículos sobre ciberseguridad, CTFs e investigaciones"
url: "https://flippermen.github.io"
repository: "flippermen/flippermen.github.io"
author:
  name: "flippermen"
  avatar: "/assets/images/avatar.jpg"
  bio: "Ingeniero En Ciberseguridad | Ethical Hacker | Pentester | CTF Player | Elite Hacker | OT Security Expert"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "haxor"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Outputting
permalink: /:title/
paginate: 10

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true
  
  # _writeups
  - scope:
      path: ""
      type: writeups
    values:
      layout: single
      author_profile: true
      share: true
      related: true

  # _certs
  - scope:
      path: ""
      type: certs
    values:
      layout: single
      author_profile: true
      share: true

# Collections
collections:
  writeups:
    output: true
    permalink: /:collection/:path/
  certs:
    output: true
    permalink: /:collection/:path/
